# Numpy Crash Course

In [1]:
import numpy as np

## Creating Arrays

In [2]:
my_list = [0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [3]:
arr = np.array(my_list) 

In [4]:
arr

array([0, 1, 2, 3, 4, 5])

In [5]:
np.arange(0,10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(0,10,5) 

array([0, 5])

In [ ]:
np.zeros((4,4))

In [ ]:
np.zeros((5,4)) 

In [ ]:
np.ones((2,4)) 

In [ ]:
np.twos((3,2)) 

In [7]:
np.random.randint(1,5)  

1

In [8]:
np.random.randint(1,10)  

4

In [15]:
np.random.randint(10,20,(3,4)) 

array([[11, 16, 14, 10],
       [16, 15, 10, 19],
       [11, 15, 14, 14]])

## Operations

In [16]:
a = np.random.randint(50,100,10)
a

array([93, 54, 94, 82, 98, 52, 60, 76, 78, 63])

In [17]:
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
arr2 = np.random.randint(0,100,10)

In [19]:
arr2

array([60, 76, 54,  7, 38, 66, 31, 76, 90, 78])

In [ ]:
arr

In [ ]:
arr.max() 

In [ ]:
arr.min()

In [ ]:
arr.mean()

In [ ]:
b1 = arr.median()

In [ ]:
a = array([1,2,3,4,9])
median(a)

In [ ]:
arr

In [ ]:
arr.reshape(3,2)  

In [ ]:
arr.reshape(2,3)

## Indexing

In [20]:
mat = np.arange(0,100).reshape(10,10) 

In [21]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [22]:
row = 6
col = 2

In [23]:
mat[row,col] 

62

In [ ]:
mat

In [24]:
# With Slices
mat[:,col] 

array([ 2, 12, 22, 32, 42, 52, 62, 72, 82, 92])

In [36]:
mat[3]

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [26]:
row=3
mat[row,:] 

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39])

In [32]:
mat[4,5]

45

In [27]:
mat[1:5,1:3,] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[11, 12],
       [21, 22],
       [31, 32],
       [41, 42]])

In [28]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [29]:
mat[1:2,1:2,]

array([[11]])

In [30]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [31]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

## Masking

In [37]:
mat # we also called as filter

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [38]:
mat > 50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [39]:
mat[mat<50] 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [44]:
a1 = mat[mat<50] 
a1.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [57]:
a2 = mat[mat>=50] 
a2.reshape([10,5])

array([[50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64],
       [65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [59]:
a2[10,2]


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

# Great Job!